# -*- coding: utf-8 -*-
"""Dictionary in Python.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1qZJ7vN_dQ63X1fuYkESM9vSrxZMm_F8d

# Create a dictionary
"""

Dict = {1: 'Hello', 2: 'World!'}
print(Dict)

dict1={} #Empty Dictionary

dict2=dict() #Empty Dictionary

dict3=dict([(1,'Hello'),(2,'World')]) #Dictionary with list of tuples

dict3

Dict4={1:'Hello',2:'World',3:{'A':'Welcome','B':'To','C':'Python'}} #Nested Dictionary
Dict4

"""# Adding Element to Dictionary"""

dictionary={}
dictionary[0]='Welcome'
dictionary[1]='To'
dictionary[2]='Python'
dictionary

"""# Accessing Elements of a Dictionary"""

Dict1={'name':'Hyundai','Model':'Elentra','Year':1990,'Varients':{1:'Hyundai Elantra VTVT S',2:'Hyundai Elantra VTVT SX',3:'Hyundai Elantra CRDi SX'}}

Dict1['name']

Dict1['Model']

Dict1['Year']

"""# Access a Value in Dictionary using get() in Python"""

Dict1.get('name')

Dict1['Varients'][1]

Dict1['Varients'][3]

"""# Deleting Element"""

del Dict1['Varients'][3]

Dict1

"""# Changing Item"""

Dict1['Model']='Verna'

Dict1

Dict1.update({"Year":2020})

Dict1

"""# Adding Items"""

Dict1['color']='white'

Dict1

Dict1.update({'Price':'2.5M'})

Dict1

"""# Removing Items"""

Dict1

Dict1.pop('Price') #The pop() method removes the item with the specified key name

Dict1

Dict1.popitem() #The popitem() method removes the last inserted item

Dict1

del Dict1['Year'] #The del keyword removes the item with the specified key name

Dict1

Dict1.clear() #The clear() method empties the dictionary

Dict1

"""# Loop Through a Dictionary"""

Dict2={'name':'Hyundai','Model':'Elentra','Year':1990,'Varients':{1:'Hyundai Elantra VTVT S',2:'Hyundai Elantra VTVT SX',3:'Hyundai Elantra CRDi SX'}}

Dict2

for x in Dict2:
    print(x) #prints the keys

for x in Dict2.values():
    print(x) #prints the values

for x in Dict2.items():
    print(x) #prints the keys and values

for x in Dict2:
    print(Dict2[x]) #prints the values

for x,y in Dict2.items():
    print(x,y) #prints the keys and values

for x in Dict2.keys():
    print(x) #prints the keys

"""# Dictionary Methods"""

Dict2

X=Dict2.copy() #The copy() method returns a copy of the dictionary

X

#The fromkeys() method returns a dictionary with the specified keys and value
#dict.fromkeys(keys, value)
x = ('key1', 'key2', 'key3')
y = 0
Dict3 = dict.fromkeys(x, y)
print(Dict3)

X=dict.fromkeys(x)
X

Dict2.get('name') #The get() method returns the value of the item with the specified key.

Dict2.setdefault('name') #The setdefault() method returns the value of the item with the specified key.

Dict2.setdefault('color ',"Blue")

Dict2

Dict2.items() #The items() method returns a list of dict's (key, value) tuple pairs

Dict2.keys() #The keys() method returns a list of all the keys in the dictionary

Dict2.values() #The values() method returns a list of all the values in the dictionary