# -*- coding: utf-8 -*-
"""Print Functions

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1gVhAtbpxGr_glo8eHAFqt-UAVhA-OdF8

# Print Function
"""

print("Hello, World!")

"""# Printing Multiple Values

"""

print("Hey","Emma","ssup")

print("Hello",11,20.56)

print?

"""Docstring:
print(value, ..., sep=' ', end='\n', file=sys.stdout, flush=False)

Prints the values to a stream, or to sys.stdout by default.

Optional keyword arguments:

file:  a file-like object (stream); defaults to the current sys.stdout.

sep:   string inserted between values, default a space.

end:   string appended after the last value, default a newline.

flush: whether to forcibly flush the stream.

Type:      builtin_function_or_method
"""

x="Hey Ram"
print(x)

"""# working with end and Separator functions"""

print("Rahul",26,sep=",")

print("Rahul",26,sep="-->")

print("Rahul",26,"Ram",36,sep="\n")

print("Rahul",26)
print("Ram",36)

print("Rahul",26,end=" ")
print("Ram",36)

print("Rahul",26,end=",")
print("Ram",36)